### PR TITLE
[greek_polytonic_greek] Adjustments to help file

### LINKED ISSUE #3187: bug(greek_polytonic_plus): missing file greek_polytonic_plus_user_guide.pdf
```
Getting links from: http://localhost:8055/keyboard/greek_polytonic_plus
├─BROKEN─ http://localhost:8055/keyboard/greek_polytonic_plus/2.0/greek_polytonic_plus_user_guide.pdf (HTTP_404)
├─BROKEN─ http://localhost:8055/keyboard/greek_polytonic_plus/2.0/greek_polytonic_plus_user_guide.pdf (HTTP_404)
```

Reported in https://github.com/keymanapp/help.keyman.com/pull/1687

The PDF needs to be added to the help folder for deployment.

Following on from #3184 -- sorry I couldn't pick this up with the earlier check, because the PHP syntax error blocked the link check.

### PR DESCRIPTION
**Pull request by LornaSIL**
I made changes in the php file syntax since it didn't seem quite right. I added the .pdf to the `help` folder.

Hopefully fixes #3187

### CODE REVIEW

**Review by DavidLRowe — APPROVED** [review]

File: release/g/greek_polytonic_plus/source/help/greek_polytonic_plus.php [hunk 1]
```diff
@@ -70,16 +58,14 @@
 	{page:WordSection1;}
 -->
 END;
+  require_once('header.php');
+?>
 
+<head>
+<meta http-equiv=Content-Type content="text/html; charset=UTF-8">
+<meta name=Generator content="Microsoft Word 15 (filtered)">
 </head>
```
Comment (mcdurdin) [inline release/g/greek_polytonic_plus/source/help/greek_polytonic_plus.php:67]: This probably should be removed too (more than 1 head tag is not really a thing for html)
