### PR TITLE
[arabic_izza] Incorporate MaleBou's revisions

### LINKED ISSUE #193: arabic_izza touch subkeys
For the phone layout for the arabic_izza touch keyboard, there are a few sets of subkeys. My impression from the text on each key is that the author is not expecting the keys to be mapped through the kmn mapping. But they are. So the keytops are wrong for what output will happen. E.g. the K_PERIOD in the default layer has subkeys and both the K_COLON and K_BACKSLASH as listed there will output \u0650.

### PR DESCRIPTION
**Pull request by darcywong00**
Using his 3 files from PR #240 to fix #193 :

* Moved `Arabic Izza.kmn` to `release/a/arabic_izza/source/arabic_izza.kmn`
* Moved `Izza3-help.htm` to `release/a/arabic_izza/source/welcome.htm`,  changed formatting of list items `<li>` to `<p>`, and copied content to `arabic_izza.php`
* Moved `Izza3-layout.js` to `release/a/arabic_izza/source/arabic_izza-layout.js`

* Added touch layout  `arabic_izza.js` to keyboard package
* Also incremented keyboard/package version from 1.0 to 1.1

### CODE REVIEW

**Comment by DavidLRowe** [comment]
@darcywong00  I wonder if the `K_BKQUOTE` entry on the third row of the default layer of the touch layout should really be `K_QUOTE` instead. There's already a `K_BKQUOTE` entry on the first row and this is the character generated by the `'` entry in the .kmn file.

**Comment by MaleBou** [comment]
Yes, you are right. The K_BKQUOTE entry on the third row of the default layer of the touch layout should  be replaced with K_QUOTE.

**Comment by darcywong00** [comment]
Hi @MaleBou , I've updated `K_BKQUOTE`, so this keyboard is ready for you to review.

**Comment by DavidLRowe** [comment]
- phone layout, default layer, third row from top, fourth key from left: id is "K_C" which invokes the `+ "c" > U+0631` rule from the .kmn file and generates U+0631; however, key's label text is U+0621, so pressing the key doesn't produce what the key says.
- phone layout, default layer, fourth row from top, third key from left: id is "K_PERIOD" which invokes the `+ "." > U+0632` rule from the .kmn file and generates U+0632; however, key's label text is U+061F, so pressing the key doesn't produce what the key says.
- phone layout, numeric layer, third row from top, all but the leftmost key: these 8 keys are not generating what the key says. For example, the second from the left is identified as "shift K_SLASH" which invokes the `+ "?" > U+061F ` rule from the .kmn file and generates U+061F; however the key's label text is `"`.

At the moment I can't test the tablet layout, but it may well have some similar issues.

**Comment by MaleBou** [comment]
All the things you mentioned are correct. I have made few more improvements and corrections since I last updated the keyboard. I'll do some more checks before submitting them.

**Comment by MaleBou** [comment]
I have just uploaded changes with some improvements to MaleBou-patch-1 branch on darcywong00/keyboards.

**Comment by MaleBou** [comment]
Changes have been uploaded to Izza branch on darcywong00/keyboards as well.

**Comment by DavidLRowe** [comment]
Looking at tablet layout (testing in Chrome on Android tablet).

tablet layout
default layer

second row down, key below the "4" key (=K_T)
longpress key text is U+064A, output is U+064E

second row down, key below the "0" key (= K_LBRKT)
longpress key text is U+0686, output is U+002B (+)

third row down, key below "3" key (= K_F)
longpress key text is U+067E, output is U+0022 (")

third row down, key below "9" key (= K_COLON)
longpress key text is U+06AF, output is U+0650

fourth row down, key below "9"/"0" (=K_PERIOD)
longpress key text is U+0698, output is U+002E (.)

fifth row, four rightmost keys, from left to right, don't output what is displayed:
text: "!", ":", U+061B, "."
output: U+0028, U+061B, U+0021, U+0029

tablet layout
shift layer

uparrow on shift key not visible (minor point)
two keys (12th from left on first row and 4th from left on second row) generate the same character U+064B

second row down, fifth from left
text is U+064A, but generates U+064E

second row down, next to rightmost key
text is U+0686, but generates "+"

second row down, rightmost key
text is "+", but generates U+064F

third row down, fourth from left
text is U+067E, but generates U+0022 (")

third row down, tenth from left
text is U+06AF, but generates U+0650

fourth row down, fourth through tenth keys (counting from left) don't output what is displayed.

**Comment by DavidLRowe** [comment]
I wonder if it would be easier to use U_xxxx for the id and the corresponding character for the text (and eliminate any layer info). For example, in the tablet layout, default layer, second row, eleventh key from left, the longpress is currently: 
```
{
  "text": "چ",
  "id": "K_LBRKT",
  "layer": "shift"
}
```
but might be clearer as:
```
{
  "text": "چ",
  "id": "U_0686"
}
```

There are still problems with the phone layout as well.

**Comment by MaleBou** [comment]
I am sorry, in my last upload I didn't include the Izza.kmn file. All the errors you mentioned are due to that. So I am going to upload it right now.

**Comment by DavidLRowe** [comment]
Where did you place the uploaded file? I'm not seeing any changes.

**Comment by MaleBou** [comment]
I have pushed it to izza branch on darcywong00/keyboards.

**Comment by darcywong00** [comment]
> I have pushed it to izza branch on darcywong00/keyboards.

I've moved those updates from the root `Arabic Izza.kmn` file to `release/a/arabic_izza/source/arabic_izza.kmn`.

How do you want to summarize these versions 1.1 updates in `history.MD?`

**Comment by MaleBou** [comment]
You could put the following;
Added extra letters (ڤ، چ، گ، پ، ژ) for writing other languages that use the Arabic script, such as Tamazight, Farsi, and Ottoman...

**Comment by DavidLRowe** [comment]
Almost there!

Looking at tablet layout (testing in Chrome on Android tablet).
tablet layout, default layer, fifth row, rightmost key, doesn't output what is displayed:
text: "."
output: U+0022

Desktop output doesn't match on-screen keyboard, but perhaps that's because the OSK wasn't updated after the swapping of keys in the .kmn file. 

Please also verify that the information in the welcome.htm is correct (after the changes to the .kmn file).

**Comment by MaleBou** [comment]
Mistake corrected. Everything looks fine to me now. Touch layout file will be uploaded in a minute.

File: release/a/arabic_izza/source/arabic_izza-layout.js [hunk 1]
```diff
@@ -242,41 +271,52 @@
...
+                "text": ":",
+                "layer": "shift"
+              },
+              {
+                "id": "K_B",
+                "text": "؛",
+                "layer": "shift"
+              },
+              {
+                "id": "K_COMMA",
```
Comment (darcywong00) [inline release/a/arabic_izza/source/arabic_izza-layout.js]: @MaleBou this line 317 seemed to be the only line that changed from your recent commit.

Comment (MaleBou) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: Yes, there is just one line that needed changing.

Comment (DavidLRowe) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: Tablet output now seems correct.

@MaleBou I think the on-screen keyboard (OSK) needs to be updated to match the changes you previously made to the .kmn file. It would be good if you could verify that the description of how to type certain characters (found in the welcome.htm) is still valid.

Comment (DavidLRowe) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: One example where OSK doesn't match keyboard is "c" and "v" keys (unshifted).

Comment (DavidLRowe) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: When you have the keyboard active and type Shift+Alt+K, the On-Screen Keyboard (OSK) should come up. I'm seeing U+0621 (ء) on the "c" key, but pressing that key produces U+0631 (ر). Similarly the OSK has U+0631 (ر) on the "v" key, but pressing that key produces U+0621 (ء). 

I don't know how many other keys on the OSK are incorrect after the change you made to the .kmn file to rearrange a number of character/key combinations. In Keyman Developer, for the On-Screen tab, one can click on the "Fill from layout" button to fill the layout with information from the .kmn file, but you may prefer to just check the keys that you recently changed.

Comment (MaleBou) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: I have both the old and new OSK on my keyman with two identical green letter ain icon. I can pivot easily between them. I have no problem. You could do the same, or reinstall the keyboard.

Comment (darcywong00) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: I'll try converting the OSK source from `.kvk` to `.kvks`.
The XML format will make it easier for us to sort this out.

Comment (DavidLRowe) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: For the OSK, shifted state, I'm seeing a discrepancy between what is on the OSK and what appears when the key is typed, for the following keys:
- second row: T { }
- third row: F : 
- fourth row: C V B N M < >

Comment (MaleBou) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: As I mentioned before, there is no discrepancy whatsoever on my side. The problem must lie somwhere in the software you are using.

Comment (MaleBou) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: As I said before, there is no discrepancy on my side. The problem must lie somewhere in the software you are using..

Comment (MaleBou) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: You are seeing the old OSK, as if no update has been done.

Comment (MaleBou) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: I am going to upload the new OSK file for you to compare with.

Comment (darcywong00) [reply release/a/arabic_izza/source/arabic_izza-layout.js]: Got it. I also Developer 10.0 "Fill from layout" to populate the OSK. Hopefully that works.

**Comment by DavidLRowe** [comment]
This corrected all the incorrect keys, but also reversed the direction of paired brackets:
- [ and ]
- < and >
- { and }
- ( and )

These symbols are bidirectional and change shape based on the direction (RTL or LTR) of the character sequence in which they are used. 

With this change, the shift-9 key has ")" displayed on the key and produces U+0029 and the shift-0 key has "(" displayed on the key and produces U+0028, however when typing Arabic the displayed character is flipped, and U+0028 shows up as ")" and U+0029 shows up as "(". I suspect that the choice of character for the OSK was deliberately changed to reflect the shape of the character when typing RTL Arabic text.

So I think the characters used on the OSK for these four pairs should be swapped. 

@MaleBou Can you confirm this? Then @darcywong00 can make the changes needed.

**Comment by MaleBou** [comment]
How can I reverse the keys from my side? They print correct as they are.

**Comment by darcywong00** [comment]
> So I think the characters used on the OSK for these four pairs should be swapped.

Done. I also updated all the Copyright dates to reflect `2017-2018`

**Comment by MaleBou** [comment]
Missing key on numeric Phone layer that enable to go back to default layer.

**Comment by MaleBou** [comment]
There is a small problem with the Phone numeric layer.A key is missing that enables going back to the default layer.
    On Monday, June 4, 2018, 5:48:25 PM GMT+1, DavidLRowe <notifications@github.com> wrote:  
 
 
Merged #248.
